面接官による面談日程の承認とメール通知機能を追加
r-yanyo/e-navigator pull request #4
Opened 2018-04-08 17:41 UTC by r-yanyo

e-navigator 後半の第2章、第3章です。

デプロイしたHerokuのURL https://e-navigator-r-yanyo.herokuapp.com/

やりたかったこと
---
- 面接官が面談日程を承認 or 拒否するための機能
- 面談日程を知らせるためのメール送信機能

やったこと
---
- ある面接日程を承認し、それ以外の日を拒否する。
- 面接日程が承認状態に変わった時に、ActionMailerによりメール通知を行う。
- ユーザは面接可能日程を追加し終えたら、面接官へ承認の申請をメールで行うことが出来る。

動作確認方法
---
- [ ] 作成したユーザでログインする。ユーザ一覧ページへ飛ぶ。
- [ ] 上部リンク「Interviews」をクリックし、ログインユーザの面接一覧を見る。
- [ ] 面接一覧ページの下部リンクで面接を申請したい人のメールアドレスを選択し、「申請」をクリックする。自分宛にも確認用のメールが送られてくることを確認する。
- [ ] ユーザ一覧ページから、ログインユーザ以外の「面接一覧」をクリックする。面接したい日の「承認する」ボタンをクリックし、面接日の承認状態が「accept」に、それ以外の日の承認状態が「reject」に切り替わることを確認。また、面接日が確定したことの確認メールが送られてくることを確認する。

2018-04-09 01:53 UTC, pokotyamu commented
見ちゃう👀

2018-04-09 02:23 UTC, pokotyamu requested changes
@r-yanyo 何点か質問もしている部分もあるのでご確認よろしくお願いします 🙋‍♂️

2018-04-09 02:23 UTC, pokotyamu commented on Gemfile
> +gem 'dotenv-rails', require: 'dotenv/rails-now'
ちょこちょこプログラムの最終行に改行が入ってないものがありますね。
エディターの設定で最終行の改行が保存時にかかるようにしておきましょう！
[なぜ最終行に改行が必要なのか - komagataのブログ](http://docs.komagata.org/5460)

2018-04-09 02:23 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  before_action :get_interview, only: [:edit, :update, :destroy, :update_acceptance]
`get_` かぁ〜 🤔 
Controller を scaffold コマンドで作った時に出来るメソッドが `set_` なもんで、そっちの方が馴染みが深いなぁという感想を持ちました。

ちなみに、 scaffold コマンドとか使ったことありますか？

2018-04-09 02:23 UTC, pokotyamu commented on config/routes.rb
> +    patch "interviews/:id", to: "interviews#update_acceptance"
put と patch の HTTP メソッドの違いで分けてますね 👀 
この２つってどう違うんでしょうか？

2018-04-09 02:23 UTC, pokotyamu commented on app/views/interviews/index.html.erb
> +    <% @interviews.order(:date).each do |interview| %>
view の中で interviews の配列をソートするのではなく、 controller から渡す段階で、ソートしてしまった方が良いです！
理由としては、view はあくまで表示のみが仕事なので、表示に関係ないロジックは Controller もしくは Model に固めてしまうのが良いからです。その方が修正スべきポイントも見つけやすいですしね 👍

2018-04-09 02:23 UTC, pokotyamu commented on app/views/interviews/index.html.erb
> +    <%= f.select :email, @users.map{|user| user.email} %>
ここも view で map するなら最初から emails を渡してみるとかどうでしょうか？ 😄

2018-04-09 02:23 UTC, pokotyamu commented on app/mailers/user_mailer.rb
> +  end
notify = 通知メールという意味か。
若干意味が広い気がしますね。
日程確定でも通知ですし、希望日確定でも通知じゃないですか？ 😄 

やりたいことは「面接を申し込む」という感じですよね？そんな感じのメソッド名にしてみましょう！

2018-04-09 02:23 UTC, pokotyamu commented on app/mailers/user_mailer.rb
> +  end
UserMailer に interview_email はちょっとイケてない感じですね 🤔 
確定したことが伝わるようなメソッド名にしてみましょう！

2018-04-09 02:23 UTC, pokotyamu commented on app/mailers/user_mailer.rb
> +end
どちらにも共通して言えることなんですが、 `_email` というのは Mailer クラスでは自明な気がするので、不要だと思います！

2018-04-09 02:36 UTC, pokotyamu commented
コメントしたことが絶対正義ではない(間違う指摘をすることもある)ので、自分はこっちの方が良いと思うんですがなどあれば、ぜひぜひコメントして下さい 🙏 

あと、隠れてしまってますが、こちらのコメントには応えて欲しいです！↓
https://github.com/r-yanyo/e-navigator/pull/4#discussion_r179973061

2018-04-09 16:43 UTC, r-yanyo commented on app/controllers/interviews_controller.rb
> +  before_action :get_interview, only: [:edit, :update, :destroy, :update_acceptance]
scaffoldはRails Tutorialでやりました。が、遥か昔のことなので覚えていないです笑

2018-04-09 16:43 UTC, r-yanyo commented on Gemfile
> +gem 'dotenv-rails', require: 'dotenv/rails-now'
VSCodeの設定で変えてみました。

2018-04-09 16:52 UTC, r-yanyo commented on config/routes.rb
> +    patch "interviews/:id", to: "interviews#update_acceptance"
最初の実装で、承認状態を「accept」に変えるときに、
”/users/:user_id/interviews/:id”にPUTして実装しようと思ったのですが、既存のPUTメソッドと被ってしまう！ということでPUTの代わりにPATCHを使うという方法を取っていました。しかし、この方法は良くないと後から気づき、その後のコミットで"/users/:user_id/interviews/:id/accept"にPUTするように変更しました。

2018-04-10 03:52 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  before_action :get_interview, only: [:edit, :update, :destroy, :update_acceptance]
なるほど。
generate コマンドはかなり便利で、 Rails を使った開発をするメリットの一つでもあります。開発スピードを上げるという意味で。
なので、ぜひ復習をしてほしいです！！！
(特にこの Interview の実装は scaffold を使って実装すれば爆速で終わるので)

2018-04-10 03:54 UTC, pokotyamu commented on config/routes.rb
> +    patch "interviews/:id", to: "interviews#update_acceptance"
> しかし、この方法は良くないと後から気づき

なるほど。実装としては、ルーティングを分けるという実装の方が良いのでその点はイイと思います 👍 
ただ、なんで良くないと思ったんでしょうか？ 🤔 
この２つを @r-yanyo さんがどう使って実装したかではなく、この２つの HTTP メソッドとしての違いを教えてほしいです！

2018-04-10 05:02 UTC, pokotyamu approved these changes
うん！動作的にも問題無いと思いました 😄 

以下２点だけ、返信もしくは修正よろしくお願いします！

- https://github.com/r-yanyo/e-navigator/pull/4#discussion_r180291044
- https://github.com/r-yanyo/e-navigator/pull/4#discussion_r180291554

2018-04-10 05:02 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      @emails = @users.pluck("email")
pluck 使ってるのめっちゃ良いですね！！！！！
pluck だと activerecord オブジェクトを生成せずに値を返すため、インスタンス生成で発生するメモリ消費などを抑えることも出来るので非常に有効です 👍

2018-04-10 05:02 UTC, pokotyamu commented on app/mailers/user_mailer.rb
> +  def request_interview(user,from_user)
うん！いい感じですね 👍

2018-04-10 05:02 UTC, pokotyamu commented on config/routes.rb
> +    post "/notify", to: "users#notify", as: "notify"
request の方がいいかなと思ったんですが、なんで戻したんでしょうか？ 🤔

2018-04-10 05:46 UTC, r-yanyo commented on config/routes.rb
> +    post "/notify", to: "users#notify", as: "notify"
まず前提として、コントローラのメソッド名とURLの末尾（ここで言うと"/notify"）の名前は統一したいと思っています。コントローラのメソッドで"request"という名前を使うと、おそらく既にある"request"というメソッドと競合する？？（ここは正直定かではないので、逆に質問したいと思っていました。）ことでバグってしまったので、止むを得ず"notify"に直しました。

2018-04-11 01:40 UTC, pokotyamu commented on config/routes.rb
> +    post "/notify", to: "users#notify", as: "notify"
[request - リファレンス - - Railsドキュメント](http://railsdoc.com/references/request)
そうか、 request と競合するのか 🙏 

そんな時は、別の単語を探すといいですね！
シソーラスとかを見て、似た意味の単語を当てるのをよくやります！
申請とかって意味の `apply` とかどうでしょう？

2018-04-11 08:04 UTC, r-yanyo commented on config/routes.rb
> +    post "/notify", to: "users#notify", as: "notify"
なるほど、変更してみます！

2018-04-12 01:25 UTC, pokotyamu commented
改めてレビューします 🙋‍♂️

2018-04-12 01:27 UTC, pokotyamu commented
動作コード共に良さそうです 🙆‍♂️ 

マージして大丈夫です 🎉 
完走お疲れ様でした！！！！！！

2018-04-12 01:32 UTC, merged